doctrine_migrations:
    migrations_paths:
        'App\Admin\Infrastructure\Migrations': '%kernel.project_dir%/migrations/Admin'
        'App\Product\Infrastructure\Migrations': '%kernel.project_dir%/migrations/Product'
    enable_profiler: false
