doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                url: '%env(resolve:DATABASE_URL_ADMIN)%'
                server_version: '9.1.0'
            product:
                url: '%env(resolve:DATABASE_URL_PRODUCT)%'
                server_version: '9.1.0'
    orm:
        auto_generate_proxy_classes: true
        proxy_dir: '%kernel.cache_dir%/doctrine/orm/Proxies'
        proxy_namespace: Proxies
        default_entity_manager: default
        entity_managers:
            default:
                connection: default
                mappings:
                    App\Admin\Infrastructure\Adapters\Persistence\Doctrine\Entities:
                        type: attribute
                        dir: '%kernel.project_dir%/src/Admin/Infrastructure/Adapters/Persistence/Doctrine/Entities'
                        prefix: 'App\Admin\Infrastructure\Adapters\Persistence\Doctrine\Entities'
                        alias: Default
            product:
                connection: product
                mappings:
                    App\Product\Infrastructure\Adapters\Persistence\Doctrine\Entities:
                        type: attribute
                        dir: '%kernel.project_dir%/src/Product/Infrastructure/Adapters/Persistence/Doctrine/Entities'
                        prefix: 'App\Product\Infrastructure\Adapters\Persistence\Doctrine\Entities'
                        alias: Product

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
