parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Product:
        resource: '../src/Product'
        exclude:
            - '../src/Product/Infrastructure/Entities'
            - '../src/Product/Domain/Entities'
